In [2]:
import numpy as np

# Reshaping Array (np.reshape()) 

In [4]:
# Create Aray 
x = np.array((range(5,14), range(6,15), range(7,16), range(8,17)))
x

array([[ 5,  6,  7,  8,  9, 10, 11, 12, 13],
       [ 6,  7,  8,  9, 10, 11, 12, 13, 14],
       [ 7,  8,  9, 10, 11, 12, 13, 14, 15],
       [ 8,  9, 10, 11, 12, 13, 14, 15, 16]])

In [5]:
np.shape(x)

(4, 9)

In [6]:
np.size(x)

36

In [ ]:
18*2 = 36 
2*18 = 36
6*6 = 36 
9*4=36
3*12 =36 
12*3=36 
5*9 =45 

In [7]:
x.reshape(9,4)

array([[ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [10]:
x.reshape(2,18)

array([[ 5,  6,  7,  8,  9, 10, 11, 12, 13,  6,  7,  8,  9, 10, 11, 12,
        13, 14],
       [ 7,  8,  9, 10, 11, 12, 13, 14, 15,  8,  9, 10, 11, 12, 13, 14,
        15, 16]])

In [11]:
x.reshape(5,5)

ValueError: cannot reshape array of size 36 into shape (5,5)

In [12]:
x.reshpe(12,4)

AttributeError: 'numpy.ndarray' object has no attribute 'reshpe'

# Indexin and Slicing of Array 

In [13]:
a = np.array(range(9,65,7))
a

array([ 9, 16, 23, 30, 37, 44, 51, 58])

In [14]:
a[0]

np.int64(9)

In [15]:
a[-1]

np.int64(58)

In [16]:
a[0:5]

array([ 9, 16, 23, 30, 37])

array([[ 5,  6,  7,  8,  9, 10, 11, 12, 13],
       [ 6,  7,  8,  9, 10, 11, 12, 13, 14],
       [ 7,  8,  9, 10, 11, 12, 13, 14, 15],
       [ 8,  9, 10, 11, 12, 13, 14, 15, 16]])

In [55]:
y=x.reshape(9,4)
y

array([[ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [20]:
y[0,3] # returns values for row '0' and col '3' 

np.int64(8)

In [21]:
y[[0,3]] # it searches for row number 0 and 3 

array([[ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [23]:
y[0:3] # returns row number 0 ,1 and 2 

array([[ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13,  6,  7,  8]])

In [ ]:
# row alwasy starts with index '0' 
# col always starts with index '0' 

In [28]:
a= ['m','n','o','p','q']
b=['a', 'e','i','o','u']
c=['p','e','r','i','x']
d=['x','y','z','j','s']
e=['k','a','t','h','m']
f=['j','a','n', 'a','k']

In [30]:
demo= np.array([a,b,c,d,e,f])


In [31]:
demo

array([['m', 'n', 'o', 'p', 'q'],
       ['a', 'e', 'i', 'o', 'u'],
       ['p', 'e', 'r', 'i', 'x'],
       ['x', 'y', 'z', 'j', 's'],
       ['k', 'a', 't', 'h', 'm'],
       ['j', 'a', 'n', 'a', 'k']], dtype='<U1')

In [32]:
np.size(demo)

30

In [33]:
np.shape(demo)

(6, 5)

In [35]:
# getting single row 
demo[0] # retruns the first row 

array(['m', 'n', 'o', 'p', 'q'], dtype='<U1')

In [36]:
demo[3] # retruns the row in index'3' 

array(['x', 'y', 'z', 'j', 's'], dtype='<U1')

In [37]:
demo[0:4] # retruns 0, 1,2,3 

array([['m', 'n', 'o', 'p', 'q'],
       ['a', 'e', 'i', 'o', 'u'],
       ['p', 'e', 'r', 'i', 'x'],
       ['x', 'y', 'z', 'j', 's']], dtype='<U1')

In [38]:
demo[0:5:2] # retuns 0 to 5 in step 2 

array([['m', 'n', 'o', 'p', 'q'],
       ['p', 'e', 'r', 'i', 'x'],
       ['k', 'a', 't', 'h', 'm']], dtype='<U1')

In [39]:
demo[1,4] # returns item in row index 1 and col index  4 

np.str_('u')

In [40]:
demo

array([['m', 'n', 'o', 'p', 'q'],
       ['a', 'e', 'i', 'o', 'u'],
       ['p', 'e', 'r', 'i', 'x'],
       ['x', 'y', 'z', 'j', 's'],
       ['k', 'a', 't', 'h', 'm'],
       ['j', 'a', 'n', 'a', 'k']], dtype='<U1')

In [41]:
demo[[1,4]] # return row index '1' and row index '4' 

array([['a', 'e', 'i', 'o', 'u'],
       ['k', 'a', 't', 'h', 'm']], dtype='<U1')

In [42]:
demo[[1,1], [2,2]] # 

array(['i', 'i'], dtype='<U1')

In [43]:
demo[1,1]

np.str_('e')

In [44]:
demo[2,2]

np.str_('r')

In [45]:
demo[[1,1],[2,2]]

array(['i', 'i'], dtype='<U1')

In [47]:
demo[[2,5],[2,4]]

array(['r', 'k'], dtype='<U1')

In [ ]:
2,2   4,4 

In [48]:
a= ['a', 'b','c','d' ,'e'] 
b= ['f','g', 'h','i','j']
c=['k','l','m','n','o']
d=['p','q','r','s','t']
e=['u','v','w','x','y']

In [50]:
demo = np.array([a,b,c,d,e])

In [51]:
np.shape(demo)

(5, 5)

In [52]:
demo 

array([['a', 'b', 'c', 'd', 'e'],
       ['f', 'g', 'h', 'i', 'j'],
       ['k', 'l', 'm', 'n', 'o'],
       ['p', 'q', 'r', 's', 't'],
       ['u', 'v', 'w', 'x', 'y']], dtype='<U1')

In [53]:
demo[[2,3],[1,4]] 

array(['l', 't'], dtype='<U1')

In [ ]:
(2,1) l (x , x) 
(3,4) t (y,y) 

In [54]:
demo[[1,4],[3,4]]

array(['i', 'y'], dtype='<U1')

In [56]:
x

array([[ 5,  6,  7,  8,  9, 10, 11, 12, 13],
       [ 6,  7,  8,  9, 10, 11, 12, 13, 14],
       [ 7,  8,  9, 10, 11, 12, 13, 14, 15],
       [ 8,  9, 10, 11, 12, 13, 14, 15, 16]])

In [57]:
y

array([[ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [60]:
# select all the values mutiple of  two '2' , from aray y'
y[y%2==0]

array([ 6,  8, 10, 12,  6,  8, 10, 12, 14,  8, 10, 12, 14,  8, 10, 12, 14,
       16])

In [61]:
y[y%3==0]

array([ 6,  9, 12,  6,  9, 12,  9, 12, 15,  9, 12, 15])

In [63]:
# Class work 
# create a 2D array which has fist 5 multiple of array of 5,6,7,8 and 9 in rows 
x= list(range(5,26,5))
x

[5, 10, 15, 20, 25]

In [67]:
xyz= np.array((range(5,26,5), range(6,31,6), range(7,36,7),range(8,41,8), range(9,46,9)))

In [68]:
xyz

array([[ 5, 10, 15, 20, 25],
       [ 6, 12, 18, 24, 30],
       [ 7, 14, 21, 28, 35],
       [ 8, 16, 24, 32, 40],
       [ 9, 18, 27, 36, 45]])

In [69]:
# filter all itemsin 'xyz' greater than 30 
xyz [xyz>30]

array([35, 32, 40, 36, 45])

In [71]:
# all multiple of 7 
xyz[xyz%7==0]

array([ 7, 14, 21, 28, 35])

In [72]:
demo

array([['a', 'b', 'c', 'd', 'e'],
       ['f', 'g', 'h', 'i', 'j'],
       ['k', 'l', 'm', 'n', 'o'],
       ['p', 'q', 'r', 's', 't'],
       ['u', 'v', 'w', 'x', 'y']], dtype='<U1')

In [ ]:
# Scalar Opetration : 
They are matematics operations performed in a single array only 
Like, if 'A' is an array
addition, subtract , multiplication, division etc are done with  a single scaler value 

In [76]:
y=np.array((range(3,9),range(4,10)))
y

array([[3, 4, 5, 6, 7, 8],
       [4, 5, 6, 7, 8, 9]])

In [77]:
y*5  # multiplis every single element of array 'y' by 5 

array([[15, 20, 25, 30, 35, 40],
       [20, 25, 30, 35, 40, 45]])

In [78]:
y % 5  # returns the result of modular division by 5 for each element in  array 'y' 

array([[3, 4, 0, 1, 2, 3],
       [4, 0, 1, 2, 3, 4]])

In [ ]:
# Class work : Create a 3*2 array and multiply each item by 6 

# Mathmatical Operation (Non Scalar) 

In [ ]:
# it requires two array of same dimenson or an array with items equal to number of columns 

In [81]:
a=[3,9,11] 
b=[21,31,61] 
d = np.array([a,b])
d

array([[ 3,  9, 11],
       [21, 31, 61]])

In [82]:
np.shape(d)

(2, 3)

In [83]:
e = d.reshape(3,2)
e

array([[ 3,  9],
       [11, 21],
       [31, 61]])

In [84]:
d+ e

ValueError: operands could not be broadcast together with shapes (2,3) (3,2) 

In [85]:
d

array([[ 3,  9, 11],
       [21, 31, 61]])

In [86]:
dx = d+2
dx

array([[ 5, 11, 13],
       [23, 33, 63]])

In [87]:
d  + dx

array([[  8,  20,  24],
       [ 44,  64, 124]])

In [88]:
d

array([[ 3,  9, 11],
       [21, 31, 61]])

In [89]:
e

array([[ 3,  9],
       [11, 21],
       [31, 61]])

In [90]:
d + e

ValueError: operands could not be broadcast together with shapes (2,3) (3,2) 

In [91]:
k =[10,20,30]
k


[10, 20, 30]

In [93]:
np.shape(k)

(3,)

In [95]:
np.shape(d)

(2, 3)

In [96]:
d

array([[ 3,  9, 11],
       [21, 31, 61]])

In [97]:
d + k

array([[13, 29, 41],
       [31, 51, 91]])

In [99]:
# Slcing and Indexing 

In [100]:
# Broadcasting array 

In [101]:
# Assigment Array ( ) 
# Python Assigment ( ) 
# A, L , R, C , M 

In [ ]:
# Python  5 pm 

In [102]:
manozkshetri3@gmail.com 

NameError: name 'manozkshetri3' is not defined

In [ ]:
# 'tensors' { numpy } [deep] 
# Braind 'Neuron' {
sevral input = output
