In [1]:
import numpy as np 

In [5]:
# create a numpy array 
x=['a', 'b', 'c', 'd', 'e'] 
y=['f', 'g','h','i','j']
z=['k', 'l','m','n','o']
a=['p', 'q', 'r','s','t']

In [6]:
demo = np.array([a, y,z,x])

In [7]:
demo

array([['p', 'q', 'r', 's', 't'],
       ['f', 'g', 'h', 'i', 'j'],
       ['k', 'l', 'm', 'n', 'o'],
       ['a', 'b', 'c', 'd', 'e']], dtype='<U1')

In [8]:
np.shape(demo)

(4, 5)

In [ ]:
        col0   col1   col2  col3  col4 
row 0 
row 1
row 2 
row 3

In [10]:
# Fetch or select a row 
demo[1] # fetch the row at index '1' 

array(['f', 'g', 'h', 'i', 'j'], dtype='<U1')

In [12]:
# fetch col 1 
demo[:,1] # it fetches column at index '1' 

array(['q', 'g', 'l', 'b'], dtype='<U1')

In [13]:
demo[:, 1:3] # it fetches colum at index 1 and 2 

array([['q', 'r'],
       ['g', 'h'],
       ['l', 'm'],
       ['b', 'c']], dtype='<U1')

In [15]:
demo[:, 1:4] # 1,2 and 3 indexd colums are returns 

array([['q', 'r', 's'],
       ['g', 'h', 'i'],
       ['l', 'm', 'n'],
       ['b', 'c', 'd']], dtype='<U1')

In [16]:
# Select or slice both row and colum values 
demo[0:3, 1:4] # it fetches row index 0 , 1 and 2 and col inde 1 , 2 and 3 

array([['q', 'r', 's'],
       ['g', 'h', 'i'],
       ['l', 'm', 'n']], dtype='<U1')

In [17]:
demo

array([['p', 'q', 'r', 's', 't'],
       ['f', 'g', 'h', 'i', 'j'],
       ['k', 'l', 'm', 'n', 'o'],
       ['a', 'b', 'c', 'd', 'e']], dtype='<U1')

In [ ]:
# Create a 6*7 array , 
# Select row from 1 to 3 
# select col from index 2 to 4 
# select row and column  1 to 3 and 4 to 7 reset

# Maths Operations 

In [24]:
x= [21,31,61,91] 
y=[101,95,17,13] 
a=[11,13,17,19]
b= [21,13,12,17]


In [25]:
check = np.array([x,y,a,b])
check

array([[ 21,  31,  61,  91],
       [101,  95,  17,  13],
       [ 11,  13,  17,  19],
       [ 21,  13,  12,  17]])

In [26]:
# sum() 
np.sum(check) # returns the sum of all item in the array 

np.int64(553)

In [27]:
np.sum(check, axis=0) # find the sum column wise 

array([154, 152, 107, 140])

In [28]:
np.sum(check, axis=1) # find sum row wise 

array([204, 226,  60,  63])

In [29]:
# mean() 
np.mean(check) # finds mean of the items in array 

np.float64(34.5625)

In [30]:
np.mean(check , axis=0) # find mean column wise

array([38.5 , 38.  , 26.75, 35.  ])

In [31]:
np.mean(check, axis=1) # finds mean row wise 

array([51.  , 56.5 , 15.  , 15.75])

In [34]:
check

array([[ 21,  31,  61,  91],
       [101,  95,  17,  13],
       [ 11,  13,  17,  19],
       [ 21,  13,  12,  17]])

In [33]:
# max() 
np.max(check)

np.int64(101)

In [35]:
np.max(check, axis=0)

array([101,  95,  61,  91])

In [36]:
np.max(check, axis=1)

array([ 91, 101,  19,  21])

In [21]:
# min() 

# BroadCasting 

In [37]:
check

array([[ 21,  31,  61,  91],
       [101,  95,  17,  13],
       [ 11,  13,  17,  19],
       [ 21,  13,  12,  17]])

In [38]:
# Add '5' in each item of check 
check + 5 

array([[ 26,  36,  66,  96],
       [106, 100,  22,  18],
       [ 16,  18,  22,  24],
       [ 26,  18,  17,  22]])

In [ ]:
# Same dimension next (add, sub , mul, div , % ) [it is also brad casting of ary] 
# one D array with elements equal to the number of colum (add, sub ,mul, %) 