# Numpy 

In [ ]:
# to use or work on numpy, we have to install it 
# in jupyter notebook , the command !pip install numpy is used 

In [3]:
!pip install numpy 

   ---------------------------------------- 0.0/12.9 MB ? eta -:--:--
   ------ --------------------------------- 2.1/12.9 MB 18.1 MB/s eta 0:00:01
   ------------------------- -------------- 8.1/12.9 MB 24.4 MB/s eta 0:00:01
   ---------------------------------------  12.8/12.9 MB 26.1 MB/s eta 0:00:01
   ---------------------------------------- 12.9/12.9 MB 22.2 MB/s  0:00:00


In [6]:
import numpy as np 

# Creating Arrays 

<h3> <b> using array() method </b> </h3>

In [7]:
np.array([1,9,8,11,16])

array([ 1,  9,  8, 11, 16])

In [8]:
# array() method is used to create, array from existing list, tuple, set  

In [9]:
# Example : from a list of number 2 to 50 , create an array 
nums = list(range(2,51))
print(nums, end=' ')

[2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50] 

In [10]:
# Create array from nums 
np.array(nums)

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18,
       19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35,
       36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50])

In [ ]:
# What is the advantages of creating an array over a list ! 

In [11]:
# from the tuple for number 3 to 30 in step 3 , create an arry 
numsx= tuple(range(3,31,3))
numsx

(3, 6, 9, 12, 15, 18, 21, 24, 27, 30)

In [12]:
np.array(numsx)

array([ 3,  6,  9, 12, 15, 18, 21, 24, 27, 30])

In [13]:
# Creating array with a set : 
# define a set 
s = set(range(1,11))
s

{1, 2, 3, 4, 5, 6, 7, 8, 9, 10}

In [14]:
# create an array 
s_aray = np.array(s) 
s_aray

array({1, 2, 3, 4, 5, 6, 7, 8, 9, 10}, dtype=object)

In [ ]:
# What is differnce between creating array from a list/ tupler and set ? 

<h3> <b> creating array with zeros </b> </h3> 

In [15]:
np.zeros((2,3)) # creates a 2 x 3 array of all zeros 

array([[0., 0., 0.],
       [0., 0., 0.]])

<h3> <b> creating array with ones </b> </h3> 

In [16]:
np.ones((2,5)), # creates an array of 2x5 with all ones 

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

<h3> <b> creating array with full </b> </h3> 

In [22]:
np.full((4,5),41) # creates an array (2x5) array filled with 13 

array([[41, 41, 41, 41, 41],
       [41, 41, 41, 41, 41],
       [41, 41, 41, 41, 41],
       [41, 41, 41, 41, 41]])

<h3> <b> creating array with arange ( )  </b> </h3> 

In [23]:
np.arange(1,10,2) # Cretes and array ranging from 1 to 10, in step 2 

array([1, 3, 5, 7, 9])

In [24]:
np.arange(-10, 10, 1)

array([-10,  -9,  -8,  -7,  -6,  -5,  -4,  -3,  -2,  -1,   0,   1,   2,
         3,   4,   5,   6,   7,   8,   9])

<h3> <b> creating array with linspace( )  </b> </h3> 

In [30]:
np.linspace(1,10,1000) # this method is used to create an array starting from 1 to 10, with spaces in 1000 

array([ 1.        ,  1.00900901,  1.01801802,  1.02702703,  1.03603604,
        1.04504505,  1.05405405,  1.06306306,  1.07207207,  1.08108108,
        1.09009009,  1.0990991 ,  1.10810811,  1.11711712,  1.12612613,
        1.13513514,  1.14414414,  1.15315315,  1.16216216,  1.17117117,
        1.18018018,  1.18918919,  1.1981982 ,  1.20720721,  1.21621622,
        1.22522523,  1.23423423,  1.24324324,  1.25225225,  1.26126126,
        1.27027027,  1.27927928,  1.28828829,  1.2972973 ,  1.30630631,
        1.31531532,  1.32432432,  1.33333333,  1.34234234,  1.35135135,
        1.36036036,  1.36936937,  1.37837838,  1.38738739,  1.3963964 ,
        1.40540541,  1.41441441,  1.42342342,  1.43243243,  1.44144144,
        1.45045045,  1.45945946,  1.46846847,  1.47747748,  1.48648649,
        1.4954955 ,  1.5045045 ,  1.51351351,  1.52252252,  1.53153153,
        1.54054054,  1.54954955,  1.55855856,  1.56756757,  1.57657658,
        1.58558559,  1.59459459,  1.6036036 ,  1.61261261,  1.62

# Creating 2D Array 

<h3> <b> Using eye()</b> </h3> 

In [41]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

<h3> <b> Using full() </b> </h3> 

In [38]:
np.full((3,5),13)

array([[13, 13, 13, 13, 13],
       [13, 13, 13, 13, 13],
       [13, 13, 13, 13, 13]])

<h3> <b> Using Ones() </b> </h3> 

In [37]:
np.ones((6,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

<h3> <b> Using Zeros() </b> </h3> 

In [36]:
np.zeros((5,6))

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

<h3> <b> Using array() </b> </h3> 

In [31]:
x = list(range(1,5))
y= list(range(2,6))

In [33]:
y

[2, 3, 4, 5]

In [34]:
np.array([x,y])

array([[1, 2, 3, 4],
       [2, 3, 4, 5]])

<h1> <b> Properties of Array </b> </h1> 

In [42]:
ex_1 = np.arange(1,10)
ex_1

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [45]:
ex_2 = np.array([range(1,10), range(2,11), range(3,12), range(4,13)])
ex_2

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9],
       [ 2,  3,  4,  5,  6,  7,  8,  9, 10],
       [ 3,  4,  5,  6,  7,  8,  9, 10, 11],
       [ 4,  5,  6,  7,  8,  9, 10, 11, 12]])

In [47]:
#ndim()  -returns the dimension of an array 
np.ndim(ex_1)

1

In [48]:
np.ndim(ex_2)

2

In [50]:
# shapes () returns rwo and columns in form of tuple 
np.shape(ex_2)

(4, 9)

In [51]:
np.size(ex_2) # returns the product of rows and column in a array, in sum it counts the number of item in an array 

36

In [56]:
#dtype() , it returns the data type of an array 
ex_2.dtype

dtype('int64')

In [ ]:
'dtype' returns the data type of an array 
ndim returns the number of dimension of array 


In [58]:
x = np.array(list(range(1,10)))

In [60]:
x

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [59]:
np.ndim(x)

1

In [61]:
y = np.array([range(3,7), range(4,8),range(5,9)])
y

array([[3, 4, 5, 6],
       [4, 5, 6, 7],
       [5, 6, 7, 8]])

In [62]:
np.ndim(y)

2

In [63]:
z = np.array([[range(3,7), range(4,8),range(5,9)]])

In [64]:
z

array([[[3, 4, 5, 6],
        [4, 5, 6, 7],
        [5, 6, 7, 8]]])

In [65]:
np.ndim(z)

3

<h1> <b> Operations in Array </b> </h1> 

<h2> <b> Arithmetic Operations </b> </h2> 

In [77]:
x= np.array([[4,9,11,13],[16,21,15,17],[19,21,81,15]])
x

array([[ 4,  9, 11, 13],
       [16, 21, 15, 17],
       [19, 21, 81, 15]])

In [80]:
np.shape(x)

(3, 4)

In [78]:
y= x-1
y

array([[ 3,  8, 10, 12],
       [15, 20, 14, 16],
       [18, 20, 80, 14]])

In [81]:
np.shape(y)

(3, 4)

In [79]:
z=np.array([[1,2],[5,6]])
z

array([[1, 2],
       [5, 6]])

In [82]:
np.shape(z)

(2, 2)

In [84]:
x

array([[ 4,  9, 11, 13],
       [16, 21, 15, 17],
       [19, 21, 81, 15]])

In [85]:
y

array([[ 3,  8, 10, 12],
       [15, 20, 14, 16],
       [18, 20, 80, 14]])

In [83]:
x + y

array([[  7,  17,  21,  25],
       [ 31,  41,  29,  33],
       [ 37,  41, 161,  29]])

In [86]:
x+z

ValueError: operands could not be broadcast together with shapes (3,4) (2,2) 

In [87]:
d= np.array([9,8,7,6])
d

array([9, 8, 7, 6])

In [88]:
x+ d

array([[13, 17, 18, 19],
       [25, 29, 22, 23],
       [28, 29, 88, 21]])

In [89]:
# subtraction 
x - y

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

In [90]:
# multiplication 
x * y 

array([[  12,   72,  110,  156],
       [ 240,  420,  210,  272],
       [ 342,  420, 6480,  210]])

In [91]:
# modular divsion 
x  % y 

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

<h2> <b> Scalar Operations </b></h2> 

In [67]:
a = np.array([[1,2,4], [10,11,16], [18,19,21]])
a

array([[ 1,  2,  4],
       [10, 11, 16],
       [18, 19, 21]])

In [68]:
# Scalar Multiplication ( * ) 
a*5 # it multiplies every single element of array by 5 

array([[  5,  10,  20],
       [ 50,  55,  80],
       [ 90,  95, 105]])

In [69]:
# scalar Divsion ( / ) 
a / 5 # divides each element of the array by 5 

array([[0.2, 0.4, 0.8],
       [2. , 2.2, 3.2],
       [3.6, 3.8, 4.2]])

In [70]:
# scalar addition ( + ) 
a + 6  # add 6 in the each elemet of array

array([[ 7,  8, 10],
       [16, 17, 22],
       [24, 25, 27]])

In [ ]:
Similarly, we have scalar subtraction , scalar modular division, scalar power 

In [ ]:
# filter the numbers divsible by 3

In [75]:
a % 6

array([[1, 2, 4],
       [4, 5, 4],
       [0, 1, 3]])

<h3> <b> Logical Operations </b> </h3> 

<h3> <b> Filters Operations </b> </h3> 

In [92]:
# Create one d  array 
np.array(range(1,5))

array([1, 2, 3, 4])

In [94]:
# Create 2 D Array 
x= np.array([range(1,5)])

In [96]:
x

array([[1, 2, 3, 4]])

In [95]:
np.ndim(x)

2

In [97]:
# create 3d Array 
np.array([[range(1,5)]])

array([[[1, 2, 3, 4]]])

In [98]:
np.ndim(np.array([[range(1,5)]]))

3

In [99]:
np.size(x)

4

In [ ]:
2*3 2d
[10, 11, 12]
[16,17,18]

In [103]:
z= np.array([[[10,11,12], [16,17,18]]])

In [104]:
np.ndim(z)

3

In [105]:
np.shape(z)

(1, 2, 3)

In [107]:
np.size(z) # product of row and colum 

6

In [ ]:
stack overflow 
web